name: Lint

on:
  - push
  - pull_request

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.1
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 17
      - name: Install packages
        run: npm ci
      - name: ESLint
        run: npm run lint
